PINECONE_API_KEY="4bdccaca-1789-427c-bd9c-84839308a05e"
OPENAI_API_KEY="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"
PINECONE_INDEX_NAME="poc-vessel-manag"
MONGODB_CONNECTION_STRING="mongodb+srv://newuser:newpassword@cluster0.o7p352n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"