PINECONE_API_KEY="4bdccaca-1789-427c-bd9c-84839308a05e"
OPENAI_API_KEY="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"
PINECONE_INDEX_NAME="poc-vessel-manag"
MONGODB_CONNECTION_STRING="mongodb+srv://newuser:newpassword@cluster0.o7p352n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"